version: '2'
services:
  api:
    build: api
    command: npm start
    volumes:
      - ./api:/usr/app
    links:
      - db
  lb:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 800:80
    links:
      - api
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
